import React from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { AlertTriangle } from 'lucide-react';

export const DisclaimerPage: React.FC = () => {
  const currentDate = new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });

  return (
    <div className="space-y-6">
      <div className="text-center space-y-2">
        <div className="flex items-center justify-center space-x-3 mb-4">
          <AlertTriangle className="h-8 w-8 text-secondary" />
          <h1 className="text-3xl font-bold">Disclaimer</h1>
        </div>
        <p className="text-muted-foreground">
          <strong>Last Updated: {currentDate}</strong>
        </p>
      </div>

      <Card className="shadow-soft border-0 border-l-4 border-l-secondary">
        <CardContent className="p-8 space-y-6">
          <p className="text-muted-foreground">
            The information provided by LearnFlow, powered by Alexzo, (the "Service") is for general informational and educational purposes only. All information on the Service is provided in good faith, however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information or AI-generated responses on the Service.
          </p>

          <section>
            <h2 className="text-xl font-semibold mb-3">AI-Generated Content</h2>
            <p>
              The responses and explanations provided by the AI are generated by Google's Gemini models. While significant efforts are made to ensure the quality and accuracy of these responses, they may sometimes contain errors, inaccuracies, or be incomplete. The AI's knowledge is based on the data it was trained on and may not always reflect the most current information or developments.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">No Professional Advice</h2>
            <p>
              The information provided by the Service is not intended to be a substitute for professional advice. Whether it's for academic, legal, medical, financial, or any other field, you should always seek the advice of a qualified professional with any questions you may have regarding a particular subject. Never disregard professional advice or delay in seeking it because of something you have read or received from this Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">Educational Use for All Ages</h2>
            <p>
              LearnFlow is designed as an educational tool suitable for learners of all ages - from children to adults. It assists with learning and understanding across various subjects and topics. The service should be used to supplement, not replace, traditional educational resources, instructors, and critical thinking. Users of all ages are encouraged to cross-verify information obtained from the Service with other reliable sources, especially for critical decisions or academic submissions. Parental guidance is recommended for younger users.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">Limitation of Liability</h2>
            <p>
              Under no circumstance shall LearnFlow or Alexzo be liable for any direct, indirect, incidental, consequential, special, or exemplary damages arising out of or in connection with your access or use of or inability to access or use the Service or any information or AI responses contained on or accessed through the Service, even if advised of the possibility of such damages. Your use of the Service is solely at your own risk.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">External Links</h2>
            <p>
              The Service may contain links to external websites that are not provided or maintained by or in any way affiliated with LearnFlow. Please note that LearnFlow does not guarantee the accuracy, relevance, timeliness, or completeness of any information on these external websites.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">No Endorsement</h2>
            <p>
              Reference to any specific commercial product, process, or service by trade name, trademark, manufacturer, or otherwise, does not necessarily constitute or imply its endorsement, recommendation, or favoring by LearnFlow or Alexzo.
            </p>
          </section>

          <div className="bg-secondary/10 p-6 rounded-lg border border-secondary/20">
            <p className="text-center font-medium">
              By using LearnFlow, you acknowledge that you have read, understood, and agree to this disclaimer.
            </p>
            <p className="text-center mt-4">
              If you have any questions regarding this disclaimer, please contact us at{' '}
              <a href="mailto:alexzomail@proton.me" className="text-primary hover:underline">
                alexzomail@proton.me
              </a>.
            </p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};