import React from 'react';
import { Card, CardContent } from '@/components/ui/card';

export const TermsPage: React.FC = () => {
  const currentDate = new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });

  return (
    <div className="space-y-6">
      <div className="text-center space-y-2">
        <h1 className="text-3xl font-bold">Terms & Conditions</h1>
        <p className="text-muted-foreground">
          <strong>Last Updated: {currentDate}</strong>
        </p>
      </div>

      <Card className="shadow-soft border-0">
        <CardContent className="p-8 space-y-6">
          <p className="text-muted-foreground">
            Welcome to LearnFlow! These terms and conditions ("Terms") outline the rules and regulations for the use of LearnFlow's Application (the "Service"), powered by Alexzo.
          </p>
          
          <p>
            By accessing or using our Service, we assume you accept these Terms in full. Do not continue to use LearnFlow if you do not agree to all of the terms and conditions stated on this page.
          </p>

          <section>
            <h2 className="text-xl font-semibold mb-3">1. License to Use</h2>
            <p className="mb-3">
              Subject to your compliance with these Terms, LearnFlow grants you a non-transferable, non-exclusive, revocable, limited license to use the Service solely for your personal, non-commercial educational purposes.
            </p>
            <p>
              You must not: Republish material from the Service without proper attribution where allowed; Sell, rent or sub-license material from the Service; Reproduce, duplicate, or copy material from the Service for commercial redistribution; Modify, adapt, translate, reverse engineer, decompile, disassemble, or create derivative works based on the Service; Use the Service in any way that is, or may be, damaging to the Service or that impacts user access to the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">2. User Content and AI Responses</h2>
            <p className="mb-3">
              Parts of this application offer an opportunity for users to submit questions (text and images - "User Content") and receive AI-generated responses ("AI Responses"). You grant LearnFlow a worldwide, irrevocable, non-exclusive, royalty-free license to use, reproduce, adapt, publish, translate and distribute your User Content in any existing or future media for the purpose of operating and improving the Service.
            </p>
            <p>
              AI Responses are generated by artificial intelligence models and are for informational and educational purposes only. LearnFlow does not filter, edit, or pre-approve AI Responses. While we strive for accuracy, AI Responses may occasionally be incorrect, incomplete, or contain biases.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">3. Disclaimer of Warranties</h2>
            <p>
              The Service is provided on an "AS IS" and "AS AVAILABLE" basis. LearnFlow makes no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information or AI Responses on the Service. Always verify critical information.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">4. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by applicable law, in no event shall LearnFlow, nor any of its officers, directors, and employees, be liable to you for anything arising out of or in any way connected with your use of this Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">5. Changes to Terms</h2>
            <p>
              LearnFlow reserves the right to revise these Terms at any time. By using this Service you are expected to review such Terms on a regular basis.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">6. Governing Law & Jurisdiction</h2>
            <p>
              These Terms will be governed by and construed in accordance with the laws of India, and you submit to the non-exclusive jurisdiction of the courts located in India for the resolution of any disputes.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">7. Contact Information</h2>
            <p>
              If you have any questions about these Terms, please contact us at{' '}
              <a href="mailto:alexzomail@proton.me" className="text-primary hover:underline">
                alexzomail@proton.me
              </a>.
            </p>
          </section>
        </CardContent>
      </Card>
    </div>
  );
};