// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpepjqqbkfswlgtduwtq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwZXBqcXFia2Zzd2xndGR1d3RxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NjUwOTUsImV4cCI6MjA2OTU0MTA5NX0.PZ6IFhb5V9RChmxjd-V23wfXdTf_d0_6yoxSirWz7hk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});