// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://geupcwswvipqxjsnguan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdldXBjd3N3dmlwcXhqc25ndWFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NDI0OTIsImV4cCI6MjA2NDUxODQ5Mn0.Ntop0kFshs7ywEINS721E1C2FYAUelMYxWaPCZ2s98E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});